package ru.damirovna.telegram.bot.constants;

public enum BotProcess {
    WAIT, SET_TIME, VERIFY_TIME, SET_EVENT_SUMMARY, SET_EVENT_START_TIME, SET_EVENT_END_TIME, SET_EVENT_LOCATION, VERIFY_EVENT_CREATION, SET_GOOGLE_CALENDAR_SAVING, EDIT_NEW_EVENT, WAIT_DATA
}
